[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.analisar]
  timeout = 26

[functions.historico]
  timeout = 10

[functions.gerar-token]
  timeout = 10

[functions.teste]
  timeout = 10

[functions.teste_gemini]
  timeout = 15
